### ISSUE TITLE
Request for Validation: Streamlining Monthly Community Meeting Registration Process

### ISSUE THREAD

**Issue by yada** [microcks/community#19]
### Describe the bug

This isn't a bug but a request to help validate the registration process for our monthly community meetings. We want to ensure the process is as smooth as possible and would appreciate feedback from those who don't yet have a Linux Foundation account. Think of this as a QA check! ;) Thanks in advance for your help.

PS: If you already have a Linux Foundation account, please confirm by reporting here that the process works as expected. ;)

### Attach any resources that can help us understand the issue.

See instructions to validate here:
https://github.com/microcks/community/blob/main/README.md#community-meetings

Looking forward to your feedback or comment to better explain the process.

**Comment by yada** [comment]
@hguerrero, Can you try to register for these meetings to see if it works as expected?

**Comment by oleg-nenashev** [comment]
Shared my feedback on Slack. TL;DR: With an existing LFX account, within a 5 minutes timebox I could not figure it out where to register

**Comment by yada** [comment]
Thanks for the feedback, @oleg-nenashev. I agree that the process is not straightforward, but it is the same for all CNCF or LF community meetings (which is not an excuse) 🥹

Let's use your experience to recap here and maybe create a short doc we can share, I'll initialize it and will greatly appreciate your review contribution on it ;)

**Comment by yada** [comment]
@oleg-nenashev please see:

#20 and the new guide here:
https://github.com/microcks/community/blob/main/JOIN-OUR-MEETINGS.md

I look forward to your comment and or validation 🙏

**Comment by oleg-nenashev** [comment]
I will submit the patch

**Comment by yada** [comment]
When #20 is validated, I'll update the README files to remove the confusing sentence regarding the LFID account and add a link to the guide.

**Comment by yada** [comment]
Thanks for the feedback @oleg-nenashev will update accordingly.

**Comment by yada** [comment]
README update with info and link to the new step by step guide ✅
